"""Application configuration shared by Streamlit views and backend helpers."""
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = APP_DIR.parent

DB_PATH = PROJECT_ROOT / "zeutec.db"
SCHEMA_PATH = PROJECT_ROOT / "schema_sqlite.sql"

PRIVATE_VISIBILITY = "PRIVATE"
SHARED_VISIBILITY = "SHARED"
PUBLIC_VISIBILITY = "PUBLIC"
READABLE_EVENT_VISIBILITY = (PUBLIC_VISIBILITY, SHARED_VISIBILITY)
VALID_EVENT_VISIBILITY = (PRIVATE_VISIBILITY, SHARED_VISIBILITY, PUBLIC_VISIBILITY)

DEMO_PASSWORD = "demo123"
PASSWORD_HASH_ITERATIONS = 120000
