"""
main.py — Zeutec Dashboard entry point.
Run with: streamlit run app/main.py
"""
import streamlit as st

st.set_page_config(
    page_title="Zeutec Dashboard",
    page_icon="🌾",
    layout="wide",
    initial_sidebar_state="expanded",
)

import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from db import authenticate_user, get_login_users, get_organizations
from config import DEMO_PASSWORD

if "user" not in st.session_state:
    st.session_state["user"] = None

st.sidebar.title("🌾 Zeutec Dashboard")
st.sidebar.markdown("---")

if st.session_state["user"] is None:
    st.title("Zeutec Dashboard")
    st.caption("Sign in with one of the seeded mock database users.")

    with st.form("login"):
        username = st.text_input("Username")
        password = st.text_input("Password", type="password")
        submitted = st.form_submit_button("Sign in", type="primary")

    if submitted:
        user = authenticate_user(username.strip(), password)
        if user:
            st.session_state["user"] = user
            st.rerun()
        else:
            st.error("Invalid username or password.")

    with st.expander("Demo credentials"):
        st.caption(f"All users generated by build.py use password: {DEMO_PASSWORD}")
        st.dataframe(get_login_users(), use_container_width=True, hide_index=True)
    st.stop()

user = st.session_state["user"]

st.sidebar.markdown(f"**{user['full_name']}**")
st.sidebar.caption(f"{user['role']} - {user['organization_name']} ({user['org_type']})")
if st.sidebar.button("Sign out"):
    st.session_state["user"] = None
    st.rerun()

st.sidebar.markdown("---")

orgs = get_organizations(user)
org_options = {f"{row['name']} ({row['org_type']})": row['organization_id'] for _, row in orgs.iterrows()}
own_org_id = int(user["organization_id"])
default_index = list(org_options.values()).index(own_org_id) if own_org_id in org_options.values() else 0

selected_label = st.sidebar.selectbox("Select Organisation", list(org_options.keys()), index=default_index)
selected_org_id = org_options[selected_label]
selected_org = orgs[orgs["organization_id"] == selected_org_id].iloc[0]

st.sidebar.markdown("---")
page = st.sidebar.radio("Page", ["📊 Overview", "🗺️ Map & Farm", "📋 Events"])

# Store selection in session state so pages can access it
st.session_state["org_id"]  = selected_org_id
st.session_state["org"]     = selected_org
st.session_state["orgs"]    = orgs
st.session_state["can_edit_selected_org"] = own_org_id == int(selected_org_id)

# ── Route to page ─────────────────────────────────────────────
if page == "📊 Overview":
    from views.overview import render
elif page == "🗺️ Map & Farm":
    from views.map_view import render
else:
    from views.events import render

render()
